# Must export PROXMOX_PASSWORD before running
---
- name: Bootstrap vm hosts
  hosts: all
  remote_user: root

  tasks:
    - name: Remove ansible enterprise repository from sources dir
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Add proxmox community repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present

    - name: Install guest tools
      apt:
        update_cache: yes
        name: libguestfs-tools
        state: latest

    - name: Set timezone
      timezone:
        name: America/Chicago

    - name: Disable ssh.socket
      ansible.builtin.systemd:
        name: ssh.socket
        enabled: no

    - name: Enable ssh.service
      ansible.builtin.systemd:
        name: ssh.service
        enabled: yes

    - name: Set authorized key for root
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"